name: Build Electron App

on:
  push:
    branches: [ widget ]  # 只在 widget 分支有推送时触发
    tags: [ 'v*' ]       # 保留版本标签触发
  pull_request:
    branches: [ widget ] # 针对 widget 分支的 PR 也触发

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install frontend dependencies
      run: |
        cd stock-monitor
        npm install

    - name: Install backend dependencies
      run: |
        cd backend
        npm install

    - name: Install root dependencies
      run: npm install

    - name: Build and package app
      run: npm run electron:build
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.os }}-build
        path: |
          dist-electron/*.dmg
          dist-electron/*.exe
        if-no-files-found: error

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist-electron/*.dmg
          dist-electron/*.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}